name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Delete win-unpacked folder
        run: |
          $releaseFolder = Get-ChildItem -Path "release" -Directory
          if ($releaseFolder.Count -eq 1) {
              $versionFolder = $releaseFolder[0]
              $path = Join-Path -Path $versionFolder.FullName -ChildPath "win-unpacked"
              if (Test-Path -Path $path) {
                  Remove-Item -Path $path -Recurse -Force
              }
          }
    

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release_on_${{ matrix. os }}
          path: release/
          retention-days: 5
